site_name: Basic Tutorial
repo_url: https://github.com/ChenMohan1010/basic-tutorial
repo_name: basic-tutorial
theme:
  name: material
  language: zh
  custom_dir: theme/
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
  palette:
    - primary: white
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
  - 首页:
    - index.md
    - 读者须知: notes/reader.md
    - 编辑者须知: notes/editor.md
  
  - 资源链接: 
    - links/index.md

  - 课程指引:
    - courses/index.md